from .cocoop import CoCoOp
from .coop import CoOp
from .dapt import DAPT
from .kgcoop import KgCoOp
from .kgcoop_dept import KgCoOpDePT
from .ivlp import IVLP
from .maple import MaPLe
from .prograd import ProGrad
from .promptsrc import PromptSRC
from .vpt import VPT
from .zsclip import ZeroShotCLIP
