from .ucp_cocoop import UCPCoCoOp
from .ucp_coop import UCPCoOp
from .ucp_dapt import UCPDAPT
from .ucp_kgcoop import UCPKgCoOp
from .ucp_kgcoop_dept import UCPKgCoOpDePT
from .ucp_ivlp import UCPIVLP
from .ucp_maple import UCPMaPLe
from .ucp_prograd import UCPProGrad
from .ucp_promptsrc import UCPPromptSRC
from .ucp_vpt import UCPVPT